[workspace]
resolver = "2"
members = [
    "crates/mgba-sys",
    "crates/frlg-emu",
    "crates/frlg-route",
    "crates/frlg-cli",
    "crates/frlg-rng",
    "crates/frlg-battle",
    "crates/frlg-mon",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1"
cc = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
png = "0.17"
serde = "1"
serde_json = "1"
sha1 = "0.10"
thiserror = "2"
zip = "2"

[profile.release]
debug = 1
