[workspace]
resolver = "2"
members = ["crates/mgba-sys", "crates/frlg-emu", "crates/frlg-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1"
cc = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
png = "0.17"
sha1 = "0.10"
thiserror = "2"

[profile.release]
debug = 1
